version: '3.7'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
      target: 'develop-stage'
    environment:
      - RUST_BACKTRACE=1
    ports:
      - "80:80"
    volumes:
      - .:/app
      - cargo-cache:/usr/local/cargo/registry
      - target-cache:/app/target
    command: /bin/sh -c "cargo watch -x 'run --bin rustknock-backend'"

volumes:
  cargo-cache:
  target-cache:
