# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - hello-actix

on:
  push:
    branches:
      - main
    paths:
      - './backend/**'
      - './quiz_json/**'
      - './quizzes.json'
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: |
          /tmp/.buildx-cache
          ./backend/target
        key: ${{ github.ref }}-${{ github.sha }}
        restore-keys: |
          ${{ github.ref }}-${{ github.sha }}
          ${{ github.ref }}
          refs/head/main

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://helloactix.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_381d46955a364ae59470fd6489486670 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_9dadfbca4f70413abce62dbd4c3360ff }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: helloactix.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_381d46955a364ae59470fd6489486670 }}/helloactix:${{ github.sha }}
        file: ./backend/Dockerfile
        context: ./
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache

    - name: Notify result to slack
      uses: homoluctus/slatify@master
      if: always()
      with:
        type: ${{ job.status }}
        job_name: "*Build hello-actix*"
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'hello-actix'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_e0c9643b00b643e19fe525f7603d2488 }}
        images: 'helloactix.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_381d46955a364ae59470fd6489486670 }}/helloactix:${{ github.sha }}'

    - name: Notify result to slack
      uses: homoluctus/slatify@master
      if: always()
      with:
        type: ${{ job.status }}
        job_name: "*Deploy hello-actix to Azure Web App*"
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}